# Backend https://decapcms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: "Creating {{collection}} “{{slug}}”"
    update: "Updating {{collection}} “{{slug}}”"
    delete: "Deleting {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Uploading “{{path}}”"
    deleteMedia: "[skip ci] Deleting “{{path}}”"

# Publish mode https://decapcms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://decapcms.org/docs/configuration-options/#media-and-public-folders
media_folder: public/images
public_folder: /images

# Collections https://decapcms.org/docs/configuration-options/#collections
collections:
  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      - label: Home
        name: home
        format: frontmatter
        file: src/index.md
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Text, name: text, widget: string }
              - { label: Tagline, name: tagline, widget: string }
              - label: Actions
                name: actions
                widget: list
                summary: '{{fields.text}} ({{fields.theme}})'
                fields:
                  - label: Theme
                    name: theme
                    widget: select
                    options: ['brand', 'alt']
                  - { label: Text, name: text, widget: string }
                  - { label: Link, name: link, widget: string }

  - label: Content
    name: content
    label_singular: 'Post'
    folder: src
    format: frontmatter
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Show Last Updated, name: lastUpdated, widget: boolean, required: false, default: false }
      - { label: Featured Image, name: featuredImage, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list }
    hide: true

  - label: Journal
    name: journal
    label_singular: 'Entry'
    folder: src
    format: frontmatter
    create: true
    nested:
      depth: 3
    slug: '{{day}}_{{slug}}'
    meta: { path: { widget: string, label: 'Path', index_file: 'index', hint: 'Separate paths with a forward slash "/" (Example: 2024/01)' } }
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Show Last Updated, name: lastUpdated, widget: boolean, required: false, default: false }
      - { label: Featured Image, name: featuredImage, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list }